# Generated by Django 4.2.29 on 2026-03-11 04:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(help_text='Supports basic HTML (bold, links).')),
                ('style', models.CharField(choices=[('info', 'Info (blue)'), ('success', 'Success (green)'), ('warning', 'Warning (yellow)'), ('promo', 'Promo (purple)')], default='info', max_length=20)),
                ('emoji', models.CharField(blank=True, default='📢', max_length=10)),
                ('is_active', models.BooleanField(default=True, verbose_name='Show to students')),
                ('show_once', models.BooleanField(default=False, help_text='If on, each student sees it only once and can dismiss it.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Announcement',
                'verbose_name_plural': 'Announcements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_id', models.CharField(help_text='ID given to the candidate, e.g. CAND001', max_length=50, verbose_name='Candidate ID')),
                ('full_name', models.CharField(max_length=200)),
                ('has_taken_test', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Candidate',
                'verbose_name_plural': 'Candidates',
            },
        ),
        migrations.CreateModel(
            name='MockTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Access Code')),
                ('title', models.CharField(max_length=200, verbose_name='Test Title')),
                ('part', models.CharField(choices=[('1.1', 'Part 1.1'), ('1.2', 'Part 1.2'), ('2', 'Part 2'), ('3', 'Part 3'), ('full', 'Full Test')], max_length=10, verbose_name='Test Part')),
                ('is_active', models.BooleanField(default=True)),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_until', models.DateTimeField(blank=True, help_text='Leave blank for no expiry', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mock Test',
                'verbose_name_plural': 'Mock Tests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Part11Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.IntegerField(help_text='e.g. 1, 2, 3', verbose_name='Question #')),
                ('text', models.TextField(verbose_name='Question Text')),
                ('prep_time_seconds', models.IntegerField(default=5, verbose_name='Prep Time (s)')),
                ('answer_time_seconds', models.IntegerField(default=45, verbose_name='Answer Time (s)')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Part 1.1 Question',
                'verbose_name_plural': 'Part 1.1 Questions',
                'ordering': ['order', 'question_number'],
            },
        ),
        migrations.CreateModel(
            name='Part12Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Internal label, e.g. 'City Life Photo Set A'", max_length=200, verbose_name='Group Title')),
                ('image', models.ImageField(help_text='Displayed for all questions in this group', upload_to='part12_images/', verbose_name='Shared Image')),
                ('context', models.TextField(blank=True, help_text='Optional: read to student before questions start', verbose_name='Image Context (read aloud)')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Part 1.2 Question Group',
                'verbose_name_plural': 'Part 1.2 Question Groups',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Part12Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.IntegerField(help_text='e.g. 4, 5, 6', verbose_name='Question #')),
                ('text', models.TextField(verbose_name='Question Text')),
                ('prep_time_seconds', models.IntegerField(default=5, verbose_name='Prep Time (s)')),
                ('answer_time_seconds', models.IntegerField(default=45, verbose_name='Answer Time (s)')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='speaking_test.part12group', verbose_name='Group')),
            ],
            options={
                'verbose_name': 'Part 1.2 Question',
                'verbose_name_plural': 'Part 1.2 Questions',
                'ordering': ['order', 'question_number'],
            },
        ),
        migrations.CreateModel(
            name='Part2Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.IntegerField(default=7, verbose_name='Question #')),
                ('text', models.TextField(help_text="e.g. 'Describe what you see and explain what might be happening.'", verbose_name='Prompt / Task')),
                ('image', models.ImageField(upload_to='part2_images/', verbose_name='Question Image')),
                ('image_caption', models.CharField(blank=True, max_length=300, verbose_name='Caption (optional)')),
                ('prep_time_seconds', models.IntegerField(default=30, verbose_name='Prep Time (s)')),
                ('answer_time_seconds', models.IntegerField(default=120, verbose_name='Answer Time (s)')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Part 2 Question',
                'verbose_name_plural': 'Part 2 Questions',
                'ordering': ['order', 'question_number'],
            },
        ),
        migrations.CreateModel(
            name='Part3Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.IntegerField(default=8, verbose_name='Question #')),
                ('text', models.TextField(help_text="e.g. 'Present arguments for and against the topic shown.'", verbose_name='Task Description')),
                ('image', models.ImageField(upload_to='part3_images/', verbose_name='Question Image')),
                ('image_caption', models.CharField(blank=True, max_length=300, verbose_name='Caption (optional)')),
                ('bullet_points', models.TextField(blank=True, help_text='Shown as on-screen hints. One per line:\n• Benefits for society\n• Economic impact\n• Your opinion', verbose_name='Bullet Points (optional)')),
                ('prep_time_seconds', models.IntegerField(default=60, verbose_name='Prep Time (s)')),
                ('answer_time_seconds', models.IntegerField(default=180, verbose_name='Answer Time (s)')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Part 3 Question',
                'verbose_name_plural': 'Part 3 Questions',
                'ordering': ['order', 'question_number'],
            },
        ),
        migrations.CreateModel(
            name='SiteAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_students', models.IntegerField(default=0)),
                ('new_students', models.IntegerField(default=0)),
                ('total_tests', models.IntegerField(default=0)),
                ('total_outsider_tests', models.IntegerField(default=0)),
                ('avg_score', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Site Analytics',
                'verbose_name_plural': 'Site Analytics',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Teacher Name')),
                ('telegram_id', models.CharField(blank=True, help_text='Get your Chat ID from @userinfobot on Telegram', max_length=100, verbose_name='Telegram Chat ID')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Teacher',
                'verbose_name_plural': 'Teachers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TestSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_type', models.CharField(choices=[('center', 'Center Student'), ('outsider', 'External Candidate')], max_length=20)),
                ('part', models.CharField(choices=[('1.1', 'Part 1.1'), ('1.2', 'Part 1.2'), ('2', 'Part 2'), ('3', 'Part 3'), ('full', 'Full Test')], max_length=10)),
                ('outsider_candidate_id', models.CharField(blank=True, max_length=100)),
                ('full_name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('started', 'Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='started', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('total_score', models.FloatField(blank=True, null=True)),
                ('rating_score', models.IntegerField(blank=True, help_text='Official rating score converted from raw score', null=True)),
                ('telegram_sent', models.BooleanField(default=False)),
                ('audio_deleted', models.BooleanField(default=False)),
                ('audio_delete_after', models.DateTimeField(blank=True, help_text='Auto-set to 2 days after completion. Cron/management command deletes files after this.', null=True)),
                ('candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='speaking_test.candidate')),
                ('mock_test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='speaking_test.mocktest')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_sessions', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='speaking_test.teacher')),
            ],
            options={
                'verbose_name': 'Test Session',
                'verbose_name_plural': 'Test Sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('streak', models.IntegerField(default=0)),
                ('last_activity', models.DateField(blank=True, null=True)),
                ('total_tests', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=False, help_text='Admin must approve before student can take tests', verbose_name='Approved')),
                ('is_blocked', models.BooleanField(default=False, help_text='Block student immediately', verbose_name='Blocked')),
                ('access_start', models.DateField(blank=True, help_text='Set automatically when you approve the student', null=True, verbose_name='Access Start Date')),
                ('access_days', models.IntegerField(blank=True, help_text='Days of unlimited access from approval. Leave blank for unlimited.', null=True, verbose_name='Access Duration (days)')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='speaking_test.teacher')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Profile',
                'verbose_name_plural': 'Student Profiles',
            },
        ),
        migrations.CreateModel(
            name='QuestionResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.IntegerField()),
                ('question_text', models.TextField(blank=True)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='recordings/%Y/%m/')),
                ('transcription', models.TextField(blank=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('score_breakdown', models.JSONField(blank=True, default=dict)),
                ('feedback', models.TextField(blank=True)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('part11_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='speaking_test.part11question')),
                ('part12_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='speaking_test.part12question')),
                ('part2_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='speaking_test.part2question')),
                ('part3_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='speaking_test.part3question')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='speaking_test.testsession')),
            ],
            options={
                'verbose_name': 'Question Response',
                'verbose_name_plural': 'Question Responses',
                'ordering': ['question_number'],
            },
        ),
        migrations.AddField(
            model_name='mocktest',
            name='teacher',
            field=models.ForeignKey(blank=True, help_text='Results sent to this teacher via Telegram', null=True, on_delete=django.db.models.deletion.SET_NULL, to='speaking_test.teacher'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='mock_test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='speaking_test.mocktest'),
        ),
        migrations.AlterUniqueTogether(
            name='candidate',
            unique_together={('mock_test', 'candidate_id')},
        ),
        migrations.CreateModel(
            name='AnnouncementDismissal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dismissed_at', models.DateTimeField(auto_now_add=True)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dismissals', to='speaking_test.announcement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Announcement Dismissal',
                'unique_together': {('announcement', 'user')},
            },
        ),
    ]
